[#ftl]
[@b.head/]
[@b.toolbar title="修改培训主题"]bar.addBack();[/@]
[@b.tabs]
  [#assign sa][#if reservationTheme.persisted]!update?id=${reservationTheme.id!}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list"]
    [@b.textfield name="reservationTheme.name" label="培训主题" value="${reservationTheme.name!}" required="true" maxlength="20"/]
    [@b.textarea name="reservationTheme.description" label="内容简介" value="${reservationTheme.description!}" maxlength="10000"/]
    [@b.formfoot]
    [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
   [/@]
  [/@]
[@b.foot/]
