[#ftl]
[@b.head/]
[@b.toolbar title="修改培训资源类型"]bar.addBack();[/@]
[@b.tabs]
  [#assign sa][#if resourceType.persisted]!update?id=${resourceType.id!}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list"]
    [@b.textfield name="resourceType.name" label="培训资源类型" value="${resourceType.name!}" required="true" maxlength="20"/]
    [@b.formfoot]
    [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
   [/@]
  [/@]
[@b.foot/]
