[#ftl]
[@b.head/]
[@b.toolbar title="预约培训"/]
[@b.grid items=reservations var="reservation"]
  [@b.gridbar]
    [#if reservations?exists && reservations?size > 0]
      bar.addItem("审核通过", action.multi('approve'));
      bar.addItem("审核不通过",action.multi('disapprove'),"edit-delete.png");
    [/#if]
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="15%" property="theme.name" title="培训主题"/]
    [@b.col width="15%" property="time.time'" title="培训时间"]${(reservation.time.time)?string('yyyy-MM-dd')}[/@]
    [@b.col width="15%" property="code" title="工号"/]
    [@b.col width="15%" property="name" title="姓名"/]
    [@b.col width="15%" property="department" title="学院或部门"/]
    [@b.col width="15%" property="tel" title="联系方式"/]
    [@b.col width="15%" property="state" title="审核状态"]${(reservation.state)}[/@]
    [/@]
  [/@]
[@b.foot/]
